export const HIGH_PROBABILITY = 0.9;
export const MODERATE_PROBABILITY = 0.75;
export const LOW_PROBABILITY = 0.6;

export enum ProbabilityRanges {
  HIGH = HIGH_PROBABILITY,
  MODERATE = MODERATE_PROBABILITY,
  LOW = LOW_PROBABILITY
};
